dics <- list()

# ordre des noms
dics[["ordre"]] <- c(
    "^albarn damon$" = "damon albarn",
    "^aubert jean louis$" = "jean louis aubert",
    "^berger michel$" = "michel berger",
    "^blunt james$" = "james blunt",
    "^bowie david$" = "david bowie",
    "^brillant dany$" = "dany brillant",
    "^casal luz$" = "luz casal",
    "^charles ray$" = "ray charles",
    "^clerc julien$" = "julien clerc",
    "^daho etienne$" = "etienne daho",
    "^derulo jason$" = "jason derulo",
    "^dessay natalie$" = "natalie dessay",
    "^diamond neil$" = "neil diamond",
    "^ezra george$" = "george ezra",
    "^fersen thomas$" = "thomas fersen",
    "^goldman jean jacques$" = "jean jacques goldman",
    "^groban josh$" = "josh groban",
    "^guetta david$" = "david guetta",
    "^hallyday johnny$" = "johnny hallyday",
    "^hepburn alex$" = "alex hepburn",
    "^jones norah$" = "norah jones",
    "^joplin janis$" = "janis joplin",
    "^knopfler mark$" = "mark knopfler",
    "^lemay lynda$" = "lynda lemay",
    "^lenorman gerard$" = "gerard lenorman",
    "^mae christophe$" = "christophe mae",
    "^mars bruno$" = "bruno mars",
    "^michael frank$" = "frank michael",
    "^pausini laura$" = "laura pausini",
    "^redding otis$" = "otis redding",
    "^sanson veronique$" = "veronique sanson",
    "^santamaria arno$" = "arno santamaria",
    "^sebastien patrick$" = "patrick sebastien",
    "^sardou michel$" = "michel sardou",
    "^sheeran ed$" = "ed sheeran",
    "^souchon alain$" = "alain souchon",
    "^vassili amaury$" = "amaury vassili",
    "^farlow$" = "tal farlow",
    "^halliday johnny$"  = "johnny hallyday",
    "^biolay benjamin$" = "benjamin biolay",
    "^cabrel francis$" = "francis cabrel",
    "^cohen avishai$" = "avishai cohen",
    "^fabian lara$" = "lara fabian",
    "^farmer mylene$" = "mylene farmer",
    "^hardy francoise$" = "francoise hardy",
    "^moire emmanuel$" = "emmanuel moire",
    "^obispo pascal$" = "pascal obispo",
    "^springsteen bruce$" = "bruce springsteen",
    "^williams pharell$" = "pharell williams",
    "^avery daniel$" = "daniel avery",
    # openrefine
    "^davis sammy jr$" = "sammy davis jr",
    "^devieilhe sabine$" = "sabine devieilhe",
    "^chopin frederic$" = "frederic chopin",
    "^mraz jason$" = "jason mraz",
    "^ringer catherine$" = "catherine ringer",
    "^carreira david$" = "david carreira",
    "^artistes divers$" = "divers artistes",
    "^didonato joyce$" = "joyce didonato",
    "^perlman itzhak$" = "itzhak perlman",
    "^pluhar christina$" = "christina pluhar",
    "^corrs \\(the\\)$" = "the corrs",
    "^insus \\(les\\)$" = "les insus",
    "^beethoven ludwig van$" = "ludwig van beethoven",
    "^cooder ry$" = "ry cooder",
    "^harnoncourt nikolaus$" = "nikolaus harnoncourt",
    "^feliciano jose$" = "jose feliciano",
    "^mozart wolfgang amadeus$" = "wolfgang amadeus mozart",
    "^rice damien$" = "damien rice",
    "^jaroussky philippe$" = "philippe jaroussky",
    "^frey glenn$" = "glenn frey",
    "^jacobs rene$" = "rene jacobs",
    "^brown jocelyn$" = "jocelyn brown",
    "^basie count$" = "count basie",
    "^young neil$" = "neil young",
    "^rossi tino$" = "tino rossi",
    "^bush kate$" = "kate bush",
    "^urban keith$" = "keith urban",
    "^kemener yann fanch$" = "yann fanch kemener",
    "^paillard jean francois$" = "jean francois paillard",
    "^o connor sinead$" = "sinead o connor",
    "^samson francois$" = "francois samson",
    "^humenry jean$" = "jean humenry",
    "^doors the$" = "the doors",
    "^sirkis nicola$" = "nicola sirkis",
    "^el khatib hanni$" = "hanni el khatib",
    "^smiths the$" = "the smiths",
    "^laurie hugh$" = "hugh laurie",
    "^depardon olivier$" = "olivier depardon",
    "^lhasa de sela$" = "lhasa",
    "^de sela lhasa$" = "lhasa",
    "^corbel \\(cecile\\)$" = "cecile corbel",
    "^davis miles$" = "miles davis",
    "^brown james$" = "james brown",
    "^salvador henri$" = "henri salvador",
    "^ann keren$" = "keren ann",
    "^kent stacey$" = "stacey kent",
    "^piaf edith$" = "edith piaf",
    "^collins phil$" = "phil collins",
    "^moustaki georges$" = "georges moustaki",
    "^rameau jean philippe$" = "jean philippe rameau",
    "^callas maria$" = "maria callas",
    "^gilmour david$" = "david gilmour",
    "^doherty peter$" = "pete doherty",
    "^peter doherty$" = "pete doherty",
    "^prigent denez$" = "denez prigent",
    "^lama serge$" = "serge lama",
    "^amos tori$" = "tori amos",
    "^minogue kylie$" = "kylie minogue",
    "^presley elvis$" = "elvis presley",
    "^quartet amadeus$" = "amadeus quartet",
    "^pop iggy$" = "iggy pop",
    "^porter gregory$" = "gregory porter",
    "^joel billy$" = "billy joel",
    "^mas jeanne$" = "jeanne mas",
    "^rimes leann$" = "leann rimes",
    "^noah yannick$" = "yannick noah",
    "^arena tina$" = "tina arena",
    "^francois claude$" = "claude francois",
    "^allen lily$" = "lily allen",
    "^sanz alejandro$" = "alejandro sanz",
    "^lewis juliette$" = "juliette lewis",
    "^mariano luis$" = "luis mariano",
    "^personne paul$" = "paul personne",
    "^bay james$" = "james bay",
    "^gabriel peter$" = "peter gabriel",
    "^duteil yves$" = "yves duteil",
    "^rivers dick$" = "dick rivers",
    "^winehouse amy$" = "amy winehouse",
    "^corea chick$" = "chick corea",
    "^jonathan joyce$" = "joyce jonathan",
    "^gershwin george$" = "george gershwin",
    "^sinatra frank$" = "frank sinatra",
    "^rolling stones the$" = "the rolling stones",
    "^offenbach jacques$" = "jacques offenbach",
    "^hart beth$" = "beth hart",
    "^isaak chris$" = "chris isaak",
    "^conte paolo$" = "paolo conte",
    "^brel jacques$" = "jacques brel",
    "^silvestri alan$" = "alan silvestri",
    "^horner james$" = "james horner",
    "^harris calvin$" = "calvin harris",
    "^francois frederic$" = "frederic francois",
    "^polnareff michel$" = "michel polnareff",
    "^kravitz lenny$" = "lenny kravitz",
    "^buble michael$" = "michael buble",
    "^zimmer hans$" = "hans zimmer",
    "^kennedy nigel$" = "nigel kennedy",
    "^chelon georges$" = "georges chelon",
    "^mendes matthieu$" = "matthieu mendes",
    "^winter johnny$" = "johnny winter",
    "^capucon renaud$" = "renaud capucon",
    "^cranberries the$" = "the cranberries",
    "^lalanne francis$" = "francis lalanne",
    "^king bb$" = "bb king",
    "^arkana keny$" = "keny arkana",
    "^fugain michel$" = "michel fugain",
    "^john eliot gardiner$" = "gardiner john eliot",
    "^mckennitt \\(loreena\\)$" = "loreena mckennitt",
    "^richard cliff$" = "cliff richard",
    "^coltrane john$" = "john coltrane",
    "^alagna roberto$" = "roberto alagna",
    "^kaempfert bert$" = "bert kaempfert",
    "^bourvil andre$" = "andre bourvil",
    "^aznavour charles$" = "charles aznavour",
    "^lady gaga bradley cooper$" = "lady gaga & bradley cooper",
    "^becaud gilbert$" = "gilbert becaud",
    "^cocker joe$" = "joe cocker",
    "^traore rokia$" = "rokia traore",
    "^shankar anoushka$" = "anoushka shankar",
    "^black keys \\(the\\)$" = "the black keys",
    "^kaas patricia$" = "patricia kaas",
    "^leloup jean$" = "jean leloup",
    "^higelin jacques$" = "jacques higelin",
    "^paul sean$" = "sean paul",
    "^brant mike$" = "mike brant",
    "^lennon john$" = "john lennon",
    "^bonamassa joe$" = "joe bonamassa",
    "^reed lou$" = "lou reed",
    "^young chris$" = "chris young",
    "^jeff beck$" = "beck jeff",
    "^benson george$" = "george benson",
    "^manset gerard$" = "gerard manset",
    "^rea chris$" = "chris rea",
    "^wilson steven$" = "steven wilson",
    "^bach johann sebastian$" = "johann sebastian bach",
    "^lamontagne ray$" = "ray lamontagne",
    "^williams john$" = "john williams",
    "^king cole nat$" = "nat king cole",
    "^rostropovitch mstislav$" = "mstislav rostropovitch",
    "^zappa frank$" = "frank zappa",
    "^wonder stevie$" = "stevie wonder",
    "^gall france$" = "france gall",
    "^nougaro claude$" = "claude nougaro",
    "^oldfield mike$" = "mike oldfield",
    "^panic\\! at the disco$" = "panic at the disco",
    "^gastinel anne$" = "anne gastinel",
    "^carey mariah$" = "mariah carey",
    "^anthony richard$" = "richard anthony",
    "^dassin joe$" = "joe dassin",
    "^clapton eric$" = "eric clapton",
    "^mothe florent$" = "florent mothe",
    "^tovati elisa$" = "elisa tovati",
    "^manson marilyn$" = "marilyn manson",
    "^manson marylin$" = "marilyn manson",
    "^pretenders the$" = "the pretenders",
    "^evora cesaria$" = "cesaria evora"
    )

# fautes d'orthographe
dics[["ortho"]] <- c(
    "^2 pac$" = "2pac",
    "^ac dc$" = "ac/dc",
    "^acdc$" = "ac/dc",
    "^anne etchegoyen le choeur aizkoa$" = "anne etchegoyen & le choeur aizkoa",
    "^b b king$" = "bb king",
    "^ben harper and the innocent criminals$" = "ben harper & the innocent criminals",
    "^black eyed peas$" = "the black eyed peas",
    "^bon jovi$" = "jon bon jovi",
    "^bruce springsteen and the e street band$" = "bruce springsteen & the e street band",
    "^buzzcocks$" = "the buzzcocks",
    "^c\\?line dion$" = "celine dion",
    "^chordettes$" = "the chordettes",
    "^christine and the queens$" = "christine & the queens",
    "^cour de pirate$" = "coeur de pirate",
    "^cranberries$" = "the cranberries",
    "^cyndi lauper$" = "cindy lauper",
    "^earth wind & fire$" = "earth wind and fire",
    "^erik frasiak$" = "eric frasiak",
    "^florence \\+ the machine$" = "florence & the machine",
    "^franck zappa$" = "frank zappa",
    "^francks michael$" = "frank michael",
    "^herbert karajan$" = "herbert von karajan",
    "von karajan herbert" = "herbert von karajan",
    "^hugues auf$" = "hugues aufray",
    "^johnny halliday$" = "johnny hallyday",
    "^julian perreta$" = "julian perretta",
    "^knopfler$" = "mark knopfler",
    "^kylie minougue$" = "kylie minogue",
    "^l oldelaf & monsieur d$" = "oldelaf et monsieur d",
    "^la laâ©gende du roi arthur$" = "la legende du roi arthur",
    "^last shadow puppets$" = "the last shadow puppets",
    "^le peuple de lherbe$" = "le peuple de l herbe",
    "^les hurlements dleo$" = "les hurlements d leo",
    "^les ogres de barbak$" = "les ogres de barback",
    "^les pr\\?tres$" = "les pretres",
    "^lilly wood and the prick$" = "lilly wood & the prick",
    "^ma\\+â«tre gims$" = "maitre gims",
    "^mireille matthieu$" = "mireille mathieu",
    "^of monsters and men$" = "of monsters & men",
    "^offspring$" = "the offspring",
    "^p!nk$" = "pink",
    "^paco de luc\\?a$" = "paco de lucia",
    "^pere duval$" = "le pere duval",
    "^pharell williams$" = "pharrell williams",
    "^pharrell willams$" = "pharrell williams",
    "^playing for change band$" = "playing for change",
    "^rockabye baby$" = "rockabye baby!",
    "^rolling stones$" = "the rolling stones",
    "^royksopp and robyn$" = "royksopp & robyn",
    "^shym$" = "shy m",
    "^simon and garfunkel$" = "simon & garfunkel",
    "^the kids united$" = "kids united",
    "^the scorpions$" = "scorpions",
    "^thelonious$" = "thelonious monk",
    "^velvet underground$" = "the velvet underground",
    "^the pink floyd$" = "pink floyd",
    "^cour de pirate$" = "coeur de pirate",
    "^harris calvin feat florence welch$" = "calvin harris",
    "^detroit \\(bertrand cantat pascal humbert\\)$" = "detroit",
    "^maison tellier \\(la\\)$" = "la maison tellier",
    "^brel$" = "jacques brel",
    "^kendji$" = "kendji girac",
    "^presley$" = "elvis presley",
    "^bebo & cigala$" = "bebo valdes & diego el cigala",
    "^cure$" = "the cure",
    "^biffy cliro" = "biffy clyro",
    "^winston mcanuff & fixiâ" = "winston mcanuff & fixi",
    "^yngwie malmsteen" = "yngwie j malmsteen",
    "^fredericks goldman jones" = "carole fredericks & jean jacques goldman & michael jones",
    "^carole fredericks & jean jacques goldman michael jones" = "carole fredericks & jean jacques goldman & michael jones",
    "^beatles$" = "the beatles",
    "^eagles$" = "the eagles",
    "^cale j j$" = "jj cale",
    "^capart \\(louis\\)" = "louis capart",
    "^charles aznavour nouveau contrat" = "charles aznavour",
    "^dylan$" = "bob dylan",
    "^dylan bob$" = "bob dylan",
    "^edith piaf chant$" = "edith piaf",
    "^eodm \\(eagles of death metal\\)$" = "eagles of death metal",
    "fatals picards \\(les\\)" = "les fatals picards",
    "^gaâ©naâ©ration goldman m pokora tal" = "m pokora & tal",
    "^generation goldman" = "artistes divers",
    "^georges brassens \\(5cd\\)" = "georges brassens",
    "^mickael jackson history futu" = "michael jackson",
    "^naked & famous the" = "the naked & famous",
    "^pink floyd atom heart mother \\(" = "pink floyd",
    "^ritchie blackmore s rainbow" = "rainbow",
    "^konono nâ°1" = "konono n1",
    "^winston mcanuff & fixiâ" = "winston mcanuff & fixi",
    "^bowie$" = "david bowie",
    "^david guetta bebe rexha & j balvin$" = "david guetta",
    "^del rey lana$" = "lana del rey",
    "^depeche mode/derek marin$" = "depeche mode",
    "^fontaine brigitte"= "brigitte fontaine",
    "^gainsbourg$" = "serge gainsbourg",
    "^gainsbourg in jazz$" = "serge gainsbourg",
    "^hallyday$" = "johnny hallyday",
    "^ibrahim maalouf / oxmo puccino$" = "ibrahim maalouf & oxmo puccino",
    "^jackson 5$" = "jackson five",
    "^jarre experience$" = "jean michel jarre",
    "^karaoke johnny hallyday$" = "johnny hallyday",
    "^karaoke michel sardou$" = "michel sardou",
    "^keen$" = "keen v",
    "^kids united nouvelle generation$" = "kids united",
    "^louane emera$" = "louane",
    "^made famous by katy perry$" = "katy perry",
    "^mae$" = "christophe mae",
    "^mae christophe/ansaldi lysa$" = "christophe mae & lysa ansaldi",
    "^maitre gims \\(feat vianney\\)$" = "maitre gims & vianney",
    "^nate dogg eminem$" = "eminem",
    "^scorpion$" = "scorpions",
    "^spirit of johnny hallyday$" = "johnny hallyday",
    "^titres rendus celebres par christophe willem$" = "christophe willem",
    #openrefine
    "^sting/shaggy$" = "sting & shaggy",
    "^thechap$" = "the chap",
    "^sixx:a m$" = "sixx am",
    "^sixx:am$"  = "sixx am",
    "^r e m$" = "rem",
    "^o s t$" = "ost",
    "^bodycount$" = "body count",
    "^jean sebastian bach$" = "johann sebastian bach",
    "^jean sebastien bach$" = "johann sebastian bach",
    "^loa\\?c nottet$" = "loic nottet",
    "^nova tune 3 6$" = "nova tunes",
    "^sydney bechet$" = "sidney bechet",
    "^alestorm$" = "halestorm",
    "^franck sinatra$" = "frank sinatra",
    "^as de tra\\?fle$" = "as de trefle",
    "^teleman$" = "telemann",
    "^david halliday$" = "david hallyday",
    "^maaetre gims$" = "maitre gims",
    "^andrea boccelli$" = "andrea bocelli",
    "^travys$" = "travis",
    "^archima\\?de$" = "archimede",
    "^hela\\?ne segara$" = "helene segara",
    "^myl\\?ne farmer$" = "mylene farmer",
    "^m mathieu chedid$" = "m",
    "^mathieu chedid$"   = "m",
    "^wax taylor$" = "wax tailor",
    "^led zeppelin 3$" = "led zeppelin",
    "^claude fran\\?ois$" = "claude francois",
    "^artic monkeys$" = "arctic monkeys",
    "^the weekend$" = "the weeknd",
    "^maria carey$" = "mariah carey",
    "^artists divers$" = "artistes divers",
    "^m\\?ns zelmerlow$" = "mans zelmerlow",
    "^lana del ray$" = "lana del rey",
    "^roy orbison$" = "roy orbinson",
    "^sages poetes de la$" = "les sages poetes de la rue",
    "^allman brothers band$" = "the allman brothers band",
    "^tit nassels$" = "les tits nassels",
    "^temptations$" = "the temptations",
    "^pretenders$" = "the pretenders",
    "^macklemore and ryan lewis$" = "macklemore & ryan lewis",
    "^donizetti g$" = "donizetti",
    "^sebastien chato$" = "el chato",
    "^sebastien el chato$" = "el chato",
    "^quatuor eba\\?ne$" = "quatuor ebene",
    "^michael schenker fest$" = "michael schenker",
    "^chats sauvages$" = "les chats sauvages",
    "^beach boys$" = "the beach boys",
    "^reinhardt/grappelli$" = "django reinhardt & stephane grappelli",
    "^mario del monaco vol iii$" = "mario del monaco",
    "^andreas scholl \\(contretenor\\)$" = "andreas scholl",
    "^stop acouphenes vol 2$" = "stop acouphenes",
    "^didier barbelivien anais$" = "didier barbelivien & anais",
    "^cast of mamma mia the movie$" = "cast of mamma mia",
    "^cast of mamma mia\\! here we go again$" = "cast of mamma mia",
    "^armstrong louis ellington duke$" = "louis armstrong & duke ellington",
    "^sylvie roucoules picat$" = "sylvie roucoules",
    "^rihana$" = "rihanna",
    "^marc andre hamelin piano$" = "marc andre hamelin",
    "^pope francesco i$" = "pape francois")

# vérification à partir des noms d'albums
dics[["verif"]] <- c(
    "^mahe$" = "yannick mahe",
    "^dion$" = "celine dion")

## artistes divers
dics[["divers"]] <- c(
    "^compilation$" = "artistes divers",
    "^divers$" = "artistes divers",
    "^multi artistes$" = "artistes divers",
    "^multi interpr\\?tes$" = "artistes divers",
    "^multi compositeurs$" = "artistes divers",
    "^multi interpretes$" = "artistes divers",
    "^various artist$" = "artistes divers",
    "^various artists$" = "artistes divers",
    "^various" = "artistes divers",
    "^variete" = "artistes divers",
    "^interpretes divers$" = "artistes divers")

# Simplifications
# on ajoute ici les modification pouvant être considérées
# comme donnant lieu à débat, notamment rapporter 
# des collectifs à leur auteur le plus connu

dics[["simplifications"]] <- c(
    "keith jarrett trio" = "keith jarrett",
    "benabar et associes" = "benabar",
    "ben harper & the innocent criminals" = "ben harper",
    "bob dylan & the band" = "bob dylan",
    "bob marley & the wailers" = "bob marley",
    "bruce springsteen & the e street band" = "bruce springsteen",
    "diana ross & the supremes" = "diana ross",
    "dire straits/knopfler" = "dire straits",
    "frank zappa & the mothers of invention" = "frank zappa",
    "jimi hendrix experience" = "jimi hendrix",
    "louis delort & the sheperds" = "louis delort",
    "manson marilyn the spooky kids" = "marilyn manson",
    ## openrefine
    "^chucho valdes and the afro cuban messengers$" = "chucho valdes",
    "brad meldhau & rossy trio" = "brad meldhau",
    "selena gomez & the scene" = "selena gomez",
    "anais delva and cast la reine des neiges and emmylou homs" = "anais delva",
    "giuseppe verdi veriano luchetti nicolai ghiaurov elena ob" = "giuseppe verdi",
    "stephen coombs (piano) holst singers stephen layton" = "stephen coombs",
    "herbert leonard christian delagrange david alexandre winter" = "herbert leonard",
    "^berliner philharmoniker herbert von karajan$" = "herbert von karajan",
    "^asaf avidan & the mojos$" = "asaf avidan",
    "^catherine ribeiro \\+ alpes$" = "catherine ribeiro",
    "the cinematic orchestra & london metropolitan orchestra" = "the cinematic orchestra",
    "robert glasper experiment" = "robert glasper",
    "roberto alagna aleksandra kurzak" = "roberto alagna",
    "^roy hargrove quintet$" = "roy hargrove",
    "^captain beefheart & his magic band$" = "captain beefheart",
    "^cliff richard & the shadows$" = "cliff richard",
    "daniel barenboim & wiener philharmoniker" = "daniel barenboim",
    "edward elgar rodolfus choir" = "edward elgar",
    "^paul van nevel and huelgas ensemble$" = "paul van nevel"
)

#### Annexes: les scripts pour diagnostiquer les problèmes

## Puis, rechercher les proximités
# library(stringdist)
# 
# performer_dist <- stringdistmatrix(unique(m$performer), method = "lv")
# performer_dist <- as.matrix(performer_dist)
# performer_dist[upper.tri(performer_dist)] <- NA
# str(performer_dist)
# dimnames(performer_dist) <- list(unique(m$performer), unique(m$performer))
# df <- as.data.frame(performer_dist) %>%
#   rownames_to_column("performer") %>%
#   as_tibble(.name_repair = "minimal") %>%
#   gather(key, value, -performer)
# 
# rp <- c("m", " ")
# 
# df <- filter(df, performer != key, !is.na(value),
#              !(performer %in% rp),
#              !(key %in% rp))
# 
# arrange(df, value) %>% write_csv(path = "stringdist.csv")
# 
# 
# group_by(m, title) %>% 
#   distinct(performer, .keep_all = TRUE) %>% 
#   mutate(n = n()) %>% 
#   arrange(desc(n), title) %>% 
#   select(title, performer, n) %>% 
#   ungroup() %>% 
#   write_csv("titres.csv")
# 
# distinct(m, performer) %>%  arrange(performer) %>% write_csv("performers.csv")

# les noms inversé à remettre dans le bon sens (bowie david -> david bowie ; à faire à la main en refaisant un extract)
# les noms de groupes: Marley & the wailers, springsteen & e-street band...
